/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Maps: typeof import('./src/components/maps.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Menubox: typeof import('./src/components/menubox.vue')['default']
    MenuBox: typeof import('./src/components/MenuBox.vue')['default']
    NaverMap: typeof import('./src/components/NaverMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
