/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('./src/components/Apps/Calendar.vue')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Cart: typeof import('./src/components/My/Cart.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    Chat: typeof import('./src/components/Apps/Chat.vue')['default']
    DashBoard: typeof import('./src/components/DashBoard.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Edit: typeof import('./src/components/Apps/Edit.vue')['default']
    Editor: typeof import('primevue/editor')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Info: typeof import('./src/components/My/Info.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Map: typeof import('./src/components/Apps/Map.vue')['default']
    Maps: typeof import('./src/components/maps.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Menubox: typeof import('./src/components/menubox.vue')['default']
    MenuBox: typeof import('./src/components/MenuBox.vue')['default']
    Msg: typeof import('./src/components/Apps/Msg.vue')['default']
    NaverMap: typeof import('./src/components/NaverMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Star: typeof import('./src/components/My/Star.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    Timeline: typeof import('primevue/timeline')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
