/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('./src/components/Apps/Calendar.vue')['default']
    Cart: typeof import('./src/components/Apps/Cart.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    DashBoard: typeof import('./src/components/DashBoard.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Map: typeof import('./src/components/Apps/Map.vue')['default']
    Maps: typeof import('./src/components/maps.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Menubox: typeof import('./src/components/menubox.vue')['default']
    MenuBox: typeof import('./src/components/MenuBox.vue')['default']
    NaverMap: typeof import('./src/components/NaverMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
